config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Home', 'action' => 'index', 'index']);

    // $routes->connect('/', ['controller' => 'Admin', 'action' => 'index', 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Tour.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Tour Entity
 *
 * @property int $tour_id
 * @property string $tour_ten
 * @property string $tour_thongtintongquat
 * @property \Cake\I18n\FrozenDate $tour_ngaydi
 * @property int $tour_songaydi
 * @property int $tour_diemdi
 * @property int $tour_diemden
 * @property int $tour_soluongtrenho
 * @property int $tour_soluongtreem
 * @property int $tour_soluongnguoilon
 * @property int $tour_dathdv
 * @property int $tour_tientt
 * @property int $loaitour_id
 * @property string $tour_hot
 * @property int $tour_trangthai
 * @property \Cake\I18n\FrozenDate $tour_thoihandk
 *
 * @property \App\Model\Entity\Tour $tour
 * @property \App\Model\Entity\Typetour $typetour
 */
class Tour extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'tour_id' => false
    ];
}

src/Model/Table/ToursTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Tours Model
 *
 * @property \App\Model\Table\ToursTable|\Cake\ORM\Association\BelongsTo $Tours
 * @property \App\Model\Table\TypetoursTable|\Cake\ORM\Association\BelongsTo $Typetours
 *
 * @method \App\Model\Entity\Tour get($primaryKey, $options = [])
 * @method \App\Model\Entity\Tour newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Tour[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Tour|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Tour patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Tour[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Tour findOrCreate($search, callable $callback = null, $options = [])
 */
class ToursTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('tours');
        $this->setDisplayField('tour_id');
        $this->setPrimaryKey('tour_id');

        $this->belongsTo('Tours', [
            'foreignKey' => 'tour_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Typetours', [
            'foreignKey' => 'loaitour_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('fromPlace', [
            'foreignKey' => 'tour_diemden',
            'joinType' => 'LEFT',
            'className' => 'Places'
        ]);
        $this->belongsTo('toPlace', [
            'foreignKey' => 'tour_diemdi',
            'joinType' => 'LEFT',
            'className' => 'Places'
        ]);
        $this->belongsToMany('who', [    
            'className' => 'Accounts', 
            'joinTable' => 'tourregisterguides',
            'foreignKey' => 'tourdkdan_tour',
            'targetForeignKey' => 'tourdkdan_user',

        ]);

    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->requirePresence('tour_ten', 'create')
            ->notEmpty('tour_ten');

        $validator
            ->requirePresence('tour_thongtintongquat', 'create')
            ->notEmpty('tour_thongtintongquat');

        $validator
            ->date('tour_ngaydi')
            ->requirePresence('tour_ngaydi', 'create')
            ->notEmpty('tour_ngaydi');

        $validator
            ->integer('tour_songaydi')
            ->requirePresence('tour_songaydi', 'create')
            ->notEmpty('tour_songaydi');

        $validator
            ->integer('tour_diemdi')
            ->requirePresence('tour_diemdi', 'create')
            ->notEmpty('tour_diemdi');

        $validator
            ->integer('tour_diemden')
            ->requirePresence('tour_diemden', 'create')
            ->notEmpty('tour_diemden');

        $validator
            ->integer('tour_soluongtrenho')
            ->allowEmpty('tour_soluongtrenho');

        $validator
            ->integer('tour_soluongtreem')
            ->allowEmpty('tour_soluongtreem');

        $validator
            ->integer('tour_soluongnguoilon')
            ->requirePresence('tour_soluongnguoilon', 'create')
            ->notEmpty('tour_soluongnguoilon');

        $validator
            ->integer('tour_dathdv')
            ->allowEmpty('tour_dathdv');

        $validator
            ->integer('tour_tientt')
            ->allowEmpty('tour_tientt');

        $validator
            ->allowEmpty('tour_hot');

        $validator
            ->integer('tour_trangthai')
            ->allowEmpty('tour_trangthai');

        $validator
            ->date('tour_thoihandk')
            ->allowEmpty('tour_thoihandk');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['tour_id'], 'Tours'));
        $rules->add($rules->existsIn(['loaitour_id'], 'Typetours'));
        return $rules;
    }
}

src/Controller/ToursController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Tours Controller
 *
 * @property \App\Model\Table\ToursTable $Tours
 *
 * @method \App\Model\Entity\Tour[] paginate($object = null, array $settings = [])
 */
class ToursController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
    }

    /**
     * View method
     *
     * @param string|null $id Tour id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function adminadd()
    {
        $this->viewBuilder()->setLayout('frontendadmin');
        $tour = $this->Tours->newEntity();
        if ($this->request->is('post')) {
            $tour = $this->Tours->patchEntity($tour, $this->request->getData());
            if ($this->Tours->save($tour)) {
                $this->Flash->success(__('The tour has been saved.'));

                return $this->redirect(['action' => 'adminindex']);
            }
            $this->Flash->error(__('The tour could not be saved. Please, try again.'));
        }
        $tours = $this->Tours->Tours->find('list', ['limit' => 200]);
        $typetours = $this->Tours->Typetours->find('list', ['limit' => 200]);
        $this->set(compact('tour', 'tours', 'typetours'));
        $this->set('_serialize', ['tour']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Tour id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */

    /**
     * Delete method
     *
     * @param string|null $id Tour id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function admindelete($id = null)
    {
        //$this->request->allowMethod(['', 'delete']);
        $tour = $this->Tours->get($id);
        if ($this->Tours->delete($tour)) {
            $this->Flash->success(__('The tour has been deleted.'));
        } else {
            $this->Flash->error(__('The tour could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'adminindex']);
    }

    public function adminindex() {
        $this->viewBuilder()->setLayout('frontendadmin');
        $this->paginate = [
        'contain' => ['Typetours', 'fromPlace', 'toPlace', 'who']
        ];
        $tours = $this->paginate($this->Tours);

        $this->set(compact('tours'));
        $this->set('_serialize', ['tours']);
    }

    public function adminedit($id = null) {
        $this->viewBuilder()->setLayout('frontendadmin');
        $tour = $this->Tours->get($id, [
            'contain' => []
            ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $tour = $this->Tours->patchEntity($tour, $this->request->getData());
            if ($this->Tours->save($tour)) {
                $this->Flash->success(__('The tour has been saved.'));

                return $this->redirect(['action' => 'adminindex']);
            }
            $this->Flash->error(__('The tour could not be saved. Please, try again.'));
        }
        $tours = $this->Tours->find('list', ['limit' => 200]);
        $typetours = $this->Tours->Typetours->find('list', ['limit' => 200]);
        $this->set(compact('tour', 'typetours'));
        $this->set('_serialize', ['tour']);
    }
    
    public function adminview($id = null) {
        $this->viewBuilder()->setLayout('frontendadmin');
        $tour = $this->Tours->get($id, [
            'contain' => ['Typetours', 'fromPlace', 'toPlace', 'who']
            ]);

        $this->set('tour', $tour);
        $this->set('_serialize', ['tour']);
        //$this->set('accounts', $accounts);
    }

    public function tourhot(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function tourhotdetail(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function toursummer(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function toursummerdetail(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function tourdomestic(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function tourdomesticdetail(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function tourabroad(){
        $this->viewBuilder()->setLayout('frontend');
    }

    public function tourabroaddetail(){
        $this->viewBuilder()->setLayout('frontend');
    }
}

src/Template/Tours/adminindex.ctp
<?= $this->element('deletemodal') ?>
<?= $this->element('Tour/addModal') ?>
<!-- menu left -->
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
  <ul class="nav menu">
    <li>
      <a href="<?= $this->url->build('Statistic/index') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Thống kê</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Account/index') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Quản lý tài khoản</a>
    </li>
    <li class="active">
      <a href="<?= $this->url->build('Tours/adminindex') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Quản lý tour</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Restaurant/index') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý nhà hàng</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Hotels/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý khách sạn</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Tickets/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý máy bay</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Blogs/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý bài viết</a>
    </li>
    <li role="presentation" class="divider"></li>
    
  </ul>
  <div class="attribution">TTQ &copy; 2017</div>
</div><!--/.sidebar-->
<!-- done menu lef id="menuli"t -->

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">     
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
      <li class="active">Admin</li>
    </ol>
  </div><!--/.row-->    

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">QUẢN LÝ TOURS</div>
        <div class="panel-body">            
          <div class="columns btn-group pull-right" style="margin-bottom: 10px;">
            <!-- delete button -->
            <button class="btn btn-default" type="button" name="toggle" title="Delete" data-toggle="modal" data-target="#deleteModal">
              <i class="glyphicon glyphicon-trash"></i>
            </button>
            <!-- import button -->
            <button class="btn btn-default" type="button" title="Import file"><i class="glyphicon glyphicon-import"></i></button>
            <!-- export -->
            <button class="btn btn-default" type="button" name="toggle" title="Export file"><i class="glyphicon glyphicon-export"></i></button>
            <!-- add Tours -->
            <a href="<?= $this->url->build(['controller' => 'Tours', 'action' => 'adminadd']) ?>"><button class="btn btn-default" type="button" name="toggle" title="Thêm Tours mới"><i class="glyphicon glyphicon-plus"></i></button></a>
          </div>
          <!-- search button -->
          <div class="pull-right search"><input class="form-control" type="text" placeholder="Search"></div>
          <!-- data table -->
          <table class="table table-striped" id="data-table">
            <!-- header -->
            <tr class="no-edit">
              <th>Check</th>
              <th>Tên Tour</th>
              <th>Ngày Đi</th>
              <th>Điểm Đi</th>
              <th>Điểm Đến</th>
              <th>Giá</th>
              <th>Tour Hot</th>
              <th>Thời Hạn Đăng Ký</th>
              <th>Thao Tác</th>
            </tr>
            <!-- dòng 1 -->
            <?php foreach ($tours as $tour): ?>
              <tr>
                <td><input type="checkbox" name=""></td>
                <td><?= h($tour->tour_ten) ?></td>
                <td><?= h($tour->tour_ngaydi) ?></td>
                <td><?= h($tour->from_place->diadiem_ten) ?></td>
                <td><?= h($tour->to_place->diadiem_ten) ?></td>
                <td><?= $this->Number->format($tour->tour_tientt) ?></td>
                <td>
                  <?php
                    if ($tour->tour_hot == 1) {
                      echo "Yes";
                    }
                    else{
                      echo "No";
                    }
                  ?>  
                </td>
                <td><?= h($tour->tour_thoihandk) ?></td>
                <td class="actions">
                  <a href="<?= $this->url->build(['controller' => 'Tours', 'action' => 'adminview', $tour->tour_id]) ?>" class="glyphicon glyphicon-eye-open"></a>
                  <a href="<?= $this->url->build(['controller' => 'Tours', 'action' => 'adminedit', $tour->tour_id]) ?>" class="glyphicon glyphicon-pencil"></a>
                  <a href="<?= $this->url->build(['controller' => 'Tours', 'action' => 'admindelete', $tour->tour_id]) ?>" class="glyphicon glyphicon-trash"></a>
                </td>
              </tr>
            <?php endforeach; ?>
          </table>
        </div>
        <!-- xong panel-body -->
      </div>
    </div>
  </div><!--/.row-->  

  <div class="row" align="right" style="margin-right: 5px;">
    <nav aria-label="Page navigation">
      <ul class="pagination phantrang">
        <li>
          <a href="" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        <li><a href="#" class="active">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">6</a></li>
        <li>
          <a href="" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      </ul>
    </nav>
  </div>
  </div><!--/.main-->

src/Template/Tours/adminview.ctp
<?= $this->element('deletemodal')?>


<!-- menu left -->
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
  <ul class="nav menu">
    <li>
      <a href="<?= $this->url->build('Statistic/index') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Thống kê</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Account/index') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Quản lý tài khoản</a>
    </li>
    <li class="active">
      <a href="<?= $this->url->build('Tours/adminindex') ?>"><svg class="glyph stroked table "><use xlink:href="#stroked-table"></use></svg> Quản lý tour</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Restaurant/index') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý nhà hàng</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Hotels/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý khách sạn</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Tickets/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý máy bay</a>
    </li>
    <li>
      <a href="<?= $this->url->build('Blogs/adminindex') ?>"><svg class="glyph stroked app-window"><use xlink:href="#stroked-app-window"></use></svg> Quản lý bài viết</a>
    </li>
    <li role="presentation" class="divider"></li>
    
  </ul>
  <div class="attribution">TTQ &copy; 2017</div>
</div><!--/.sidebar-->
<!-- done menu lef id="menuli"t -->

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">     
  <div class="row">
    <ol class="breadcrumb">
      <li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
      <li class="active">Admin</li>
    </ol>
  </div><!--/.row-->    

  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">QUẢN LÝ TOUR</div>
        <div class="panel-body">            
          <div class="columns btn-group pull-right" style="margin-bottom: 10px;">
            <!-- delete button -->
            <button class="btn btn-default" type="button" name="toggle" title="Delete">
              <i class="glyphicon glyphicon-trash" data-toggle="modal" data-target="#deleteModal"></i>
            </button>
          </div>
          <!-- data table -->
          <table class="table table-striped" id="data-table">
            <!-- header -->
            <tr>
              <th width="200px">ID</th>
              <td class="no-edit"><?= h($tour->tour_id) ?></td>
            </tr>
            <!-- dòng 1 -->
            <tr>
              <th>Tên Tour</th>                
              <td class="no-edit"><?= h($tour->tour_ten) ?></td>
            </tr>
            <tr>
              <th>Thông Tin Tổng Quát</th>
              <td class="no-edit"><?= h($tour->tour_thongtintongquat) ?></td>
            </tr>
            <tr>
             <th>Loại Tour</th>
             <td class="no-edit"><?= h($tour->typetour->loaitour_ten) ?></td>
           </tr>
           <tr>
             <th>Số Ngày Đi</th>
             <td class="no-edit"><?= $this->Number->format($tour->tour_songaydi) ?></td>
           </tr>
           <tr>
            <th>Điểm Đi</th>
            <td class="no-edit">
              <?= h($tour->from_place->diadiem_ten) ?>
            </td>
          </tr>
          <tr>
            <th>Điểm Đến</th>
            <td class="no-edit"><?= h($tour->to_place->diadiem_ten) ?></td>
          </tr>
          <tr>
            <th>Tour Hot</th>
            <td>
              <?php
              if ($tour->tour_hot == 1) {
                echo "Yes";
              }
              else{
                echo "No";
              }
              ?>  
            </td>
          </tr>
          <tr>
           <th>Hướng Dẫn Viên</th>
           <td class="no-edit">
            <ul>
             <?php
             foreach ($tour->who as $value) {
               echo '<li>'.$value['user_ten'].'</li>' ;
             }
             ?>
           </ul>
         </td>
       </tr>
       <tr>
         <th>Giá</th>
         <td class="no-edit"><?= $this->Number->format($tour->tour_tientt) ?></td>
       </tr>
       <tr>
         <th>Trạng Thái</th>
         <td class="no-edit"><?= $this->Number->format($tour->tour_trangthai) ?></td>
       </tr>
     </table>

   </div>
   <!-- xong panel-body -->
 </div>
 <!-- xong div panel -->
</div>
<!-- xong div col-md-12 -->
</div>
<!--/.row--> 
</div>

</div><!--/.main-->

src/Template/Tours/index.ctp
<?php
/**
  * @var \App\View\AppView $this
  * @var \App\Model\Entity\Tour[]|\Cake\Collection\CollectionInterface $tours
  */
?>
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Tour'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Typetours'), ['controller' => 'Typetours', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Typetour'), ['controller' => 'Typetours', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="tours index large-9 medium-8 columns content">
    <h3><?= __('Tours') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th>Check</th>
                <th scope="col"><?= $this->Paginator->sort('tour_ten') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_ngaydi') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_diemdi') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_diemden') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_tientt') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_hot') ?></th>
                <th scope="col"><?= $this->Paginator->sort('tour_thoihandk') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tours as $tour): ?>
            <tr>
                <td><input type="checkbox" name=""></td>
                <td><?= h($tour->tour_ten) ?></td>
                <td><?= h($tour->tour_ngaydi) ?></td>
                <td><?= $this->Number->format($tour->tour_diemdi) ?></td>
                <td><?= $this->Number->format($tour->tour_diemden) ?></td>
                <td><?= $this->Number->format($tour->tour_tientt) ?></td>
                <td><?= h($tour->tour_hot) ?></td>
                <td><?= h($tour->tour_thoihandk) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $tour->tour_id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $tour->tour_id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $tour->tour_id], ['confirm' => __('Are you sure you want to delete # {0}?', $tour->tour_id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->first('<< ' . __('first')) ?>
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
            <?= $this->Paginator->last(__('last') . ' >>') ?>
        </ul>
        <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
    </div>
</div>